services:
  frontend:
    container_name: taw-frontend
    hostname: taw-frontend
    build: ./taw-frontend
    volumes:
      - ./taw-frontend/src:/app/src
    ports:
      - "4200:4200"
    networks:
      taw-network:
        ipv4_address: 172.77.0.7
    depends_on: [backend]
  backend:
    container_name: taw-backend
    hostname: taw-backend
    build: ./taw-backend
    volumes:
      - ./taw-backend/src:/app/src
      - ./taw-backend/models:/app/models
      - ./taw-backend/config:/app/config
    env_file:
      - ./taw-backend/.env
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      taw-network:
        ipv4_address: 172.77.0.17
    depends_on: [mongodb]
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - ./dbdata/mongo_data/data:/data/db/
      - ./dbdata/mongo_data/db_config:/data/configdb/
    env_file:
      - ./taw-backend/.env
    networks:
      taw-network:
        ipv4_address: 172.77.0.27
networks:
  taw-network:
    ipam:
      config:
        - subnet: 172.77.0.0/24
          gateway: 172.77.0.1
