services:
  frontend:
    container_name: taw-frontend
    build: ./taw-frontend
    volumes:
      - ./taw-frontend/src:/app/src
    ports:
      - "4200:4200"
  backend:
    container_name: taw-backend
    build: ./taw-backend
    volumes:
      - ./taw-backend/src:/app/src
    environment:
      - MONGODB_URL=${DATABASE_URL}
    ports:
      - "3000:3000"