services:
  frontend:
    container_name: taw-frontend
    build: ./taw-frontend
    ports:
      - "4200:4200"
  backend:
    container_name: taw-backend
    build: ./taw-backend
    environment:
      - MONGODB_URL=${DATABASE_URL}
    ports:
      - "3000:3000"